export interface IconComponentConfig {
    description: string,
    importDir: string,
    icons: string[],
    lazyIcons: string[],
    time: boolean,
    componentName: string,
    cssClass: string,
    wrapNamespace: boolean,
    customCode: string,
}

export function generateIconComponent({
    description,
    importDir,
    icons,
    lazyIcons,
    time,
    cssClass,
    componentName,
    wrapNamespace,
    customCode,
}: IconComponentConfig) {

    const iconImports = icons.map((i, idx) => `import _${idx} from '${importDir}/${i}';`).join('\n');
    const lazyIconImports = lazyIcons.map((i, idx) => `const _${idx}_lz = React.lazy(() => import('${importDir}/${i}'));`).join('\n');
    let iconMapKeys: string =
        icons.map((i, idx) => `"${i}": _${idx},`).join('\n') +
        lazyIcons.map((i, idx) => `"${i}": _${idx}_lz,`).join('\n');

    const propsExtends = " extends React.ComponentPropsWithRef<'svg'>";

    const propsInterface = wrapNamespace
        ? ''
        : `\
export interface ${componentName}Props${propsExtends} {
    children: string;
}
`;

    const namespaceExport = wrapNamespace
        ? `\
export namespace ${componentName} {
    export interface Props${propsExtends} {
        children: string;
    }
}
`
        : '';

    const propsInterfaceName = wrapNamespace
        ? `${componentName}.Props`
        : `${componentName}Props`;

    return `\
//@eslint-disable-file
/**
 * Generated by react-gen
 * 
${description ? ' * ' + description + '\n\n' : ''}\
 * The changes will be lost the next time you update the icons.
 * Define custom code snippet in the configuartion file if needed.
${time ? " * @time " + new Date().toLocaleString() : ''}
 */
${customCode}
import React, { Suspense } from 'react';

/**
 * The "missing" icon and the "loading" icon.
 * 
 * Replace with your own by renaming your icon file the same as below.
 */
import __missing from '${importDir}/__missing';
import __loading from '${importDir}/__loading';

// Import icons
${iconImports}

// Import icons lazily
${lazyIconImports}

// Build icon map
const iconMap = {
    ${iconMapKeys}
 };

${propsInterface}\
export const ${componentName} = React.forwardRef<SVGSVGElement, ${propsInterfaceName}>(({
    children, className = '', style, ...otherProps
}, ref) => {

    // Validate props "children"
    if (typeof children !== 'string')
        throw new Error("[${componentName}] Invalid child type. Use icon name string to access icons.");

    // Access the icon component in the object map
    const IconComponent = iconMap[children] || __missing;

    return (
        <Suspense fallback={<__loading data-icon-name='__loading' className={\`${cssClass} \${className}\`} />}>
            <IconComponent data-icon-name={children} className={\`${cssClass} \${className}\`} {...otherProps} ref={ref} />
        </Suspense>
    );
})

${namespaceExport}\
`
}

export function generateIcon(svgContent: string) {

    const svgContentWithProps = svgContent.replace(/(?<=<svg[\s\S]*?(?=>))>/, " {...props} ref={ref}>");

    return `\
import React from "react";\
export default React.forwardRef<SVGSVGElement, React.SVGAttributes<SVGSVGElement>>((props, ref): JSX.Element => ${svgContentWithProps});`
}